---
originRequest:
  originServerName: "external.${SECRET_DOMAIN}"

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: https://traefik-external.network.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
  - hostname: "*.${SECRET_DOMAIN}"
    service: https://traefik-external.network.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
  - hostname: "siggerzz.io"
    service: https://traefik-external.network.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
  - hostname: "*.siggerzz.io"
    service: https://traefik-external.network.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
  - service: http_status:404
