---
metrics:
  - name: cluster_node_count
    query: count(kube_node_info)
    label: Nodes
    color: blue

  - name: cluster_pod_count
    query: sum(kubelet_running_pods)
    label: Pods
    color: green

  - name: cluster_cpu_usage
    query: round(100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100), 0.1)
    label: CPU
    suffix: "%"
    color: orange

  - name: cluster_memory_usage
    query: round(sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes) * 100, 0.1)
    label: Memory
    suffix: "%"
    color: blue

  - name: cluster_uptime_days
    query: round(avg(node_time_seconds - node_boot_time_seconds) / 86400)
    label: Uptime
    suffix: "d"
    color: brightgreen
