---
# yaml-language-server: $schema=https://raw.githubusercontent.com/kashalls/kromgo/main/config.schema.json
badge:
  font: Verdana.ttf
  size: 12

metrics:
  - name: cluster_node_count
    query: count(kube_node_info)
    colors:
      - {color: "green", min: 0, max: 9999}
    title: Nodes

  - name: cluster_pod_count
    query: sum(kubelet_running_pods)
    colors:
      - {color: "green", min: 0, max: 9999}
    title: Pods

  - name: cluster_cpu_usage
    query: round(100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100), 0.1)
    suffix: "%"
    colors:
      - {color: "green", min: 0, max: 35}
      - {color: "orange", min: 36, max: 75}
      - {color: "red", min: 76, max: 9999}
    title: CPU

  - name: cluster_memory_usage
    query: round(sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes) * 100, 0.1)
    suffix: "%"
    colors:
      - {color: "green", min: 0, max: 35}
      - {color: "orange", min: 36, max: 75}
      - {color: "red", min: 76, max: 9999}
    title: Memory

  - name: cluster_uptime_days
    query: round(avg(node_time_seconds - node_boot_time_seconds) / 86400)
    suffix: "d"
    colors:
      - {color: "green", min: 0, max: 180}
      - {color: "orange", min: 181, max: 360}
      - {color: "red", min: 361, max: 9999}
    title: Uptime
